# Generated by Django 2.0.5 on 2018-07-05 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20180705_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='room_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rooms.Room'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='additional_information_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='affiliation',
            field=models.CharField(blank=True, choices=[('f', 'Faculty'), ('t', 'staff'), ('s', 'Student'), ('v', 'Visitor'), ('o', 'Other')], default='f', help_text='Affiliation with the SON', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
