# Generated by Django 2.0.5 on 2018-07-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20180705_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='pending_tickets',
        ),
        migrations.AddField(
            model_name='room',
            name='no_new_tickets',
            field=models.BooleanField(default=True),
        ),
    ]
