# Generated by Django 2.0.5 on 2018-07-05 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20180705_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['no_new_tickets']},
        ),
    ]
