# Generated by Django 2.0.5 on 2018-07-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20180710_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='identifier',
        ),
    ]
