# Generated by Django 2.0.5 on 2018-07-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_remove_room_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='column',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third')], default='1', help_text='PLEASE DO NOT CHANGE THIS.  Positioning of the room when in grid view on the dashboard.', max_length=1),
        ),
    ]
