# Generated by Django 2.0.5 on 2018-07-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_room_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='column',
        ),
    ]
