# Generated by Django 2.0.5 on 2018-07-05 18:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('details', models.TextField()),
                ('floorplan', models.ImageField(null=True, upload_to='')),
                ('status', models.CharField(blank=True, choices=[('r', 'Red'), ('y', 'Yellow'), ('g', 'Green')], default='g', help_text='Status of the room', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_number', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular ticket across all the available tickets', primary_key=True, serialize=False)),
                ('additional_information_feedback', models.TextField()),
                ('affiliation', models.CharField(blank=True, choices=[('f', 'Faculty'), ('t', 'staff'), ('s', 'Student'), ('v', 'Visitor'), ('o', 'Other')], default='f', help_text='Affiliation with the SON', max_length=1)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
