# Generated by Django 2.0.5 on 2018-07-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='floorplan',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
